name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - name: npm install
        run: |
          npm ci
          npm run build
        env:
          CI: true
      - name: jest
        run: |
          npm test
        env:
          CI: true
      - uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests 
          file: ./coverage/cobertura-coverage.xml
          name: jest
      - name: e2e
        run: |
          npm run e2e
        env:
          CI: true
      - uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests 
          file: e2e_coverage/lcov.info
          name: node
